name: Build

# TODO: update if you want to allow from forked repositories
on: [pull_request]

env:
  # TODO: Update the below variables for your project
  APP_NAME: "Template"
  IDF_TARGET: 'esp32'
  IDF_VERSION: 'v5.5'
  IDF_COMPONENT_MANAGER: "1" # whether to enable the component manager or not
  FLASH_TOTAL_OVERRIDE: '1500000' # number of bytes of total flash (for percentage calculations)

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
      # TODO: update this if you have submodules

    - name: Build main
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.IDF_VERSION }}
        path: "."
        target: ${{ env.IDF_TARGET }}

    - name: Determine Size Delta
      uses: esp-cpp/esp-idf-size-delta@v1
      with:
        app_name: ${{ env.APP_NAME }}
        app_path: "."
        idf_target: ${{ env.IDF_TARGET }}
        idf_version: ${{ env.IDF_VERSION }}
        idf_component_manager: ${{ env.IDF_COMPONENT_MANAGER }}
        flash_total_override: ${{ env.FLASH_TOTAL_OVERRIDE }}
