name: 'ESP-IDF Size Delta (Release)'

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  # TODO: Update the below variables for your project
  APP_NAME: "Template"
  IDF_TARGET: 'esp32'
  IDF_VERSION: 'v5.5'
  IDF_COMPONENT_MANAGER: "1" # whether to enable the component manager or not
  FLASH_TOTAL_OVERRIDE: '1500000' # number of bytes of total flash (for percentage calculations)

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Checkout repo to get tags
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine base ref
      id: base
      shell: bash
      run: |
        set -euo pipefail
        COMPARE_TAG_INPUT="${{ github.event.inputs.compare_tag || '' }}"
        if [ -n "$COMPARE_TAG_INPUT" ]; then
          echo "ref=$COMPARE_TAG_INPUT" >> "$GITHUB_OUTPUT"
        else
          # use the previous tag chronologically
          prev=$(git tag --sort=-creatordate | sed -n '2p')
          if [ -z "$prev" ]; then prev=$(git tag --sort=-v:refname | sed -n '2p'); fi
          echo "ref=$prev" >> "$GITHUB_OUTPUT"
        fi

    - name: Determine Size Delta
      uses: esp-cpp/esp-idf-size-delta@main
      with:
        app_name: ${{ env.APP_NAME }}
        app_path: "."
        idf_target: ${{ env.IDF_TARGET }}
        idf_version: ${{ env.IDF_VERSION }}
        idf_component_manager: ${{ env.IDF_COMPONENT_MANAGER }}
        base_ref: ${{ steps.base.outputs.ref }}
        flash_total_override: ${{ env.FLASH_TOTAL_OVERRIDE }}
        post_comment: 'false'
